# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-29 07:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0002_auto_20160927_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='topic_resume',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
